[project]
name = "qdrantdb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.93.0",
    "qdrant-client>=1.14.3",
    "streamlit>=1.46.1",
    "streamlit-openai>=0.1.4",
]
