# kafka.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  replicas: 1
  serviceName: kafka-svc
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        runAsUser: 0
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            - sh
            - -c
            - |
              chown -R 1000:1000 /var/lib/kafka/data
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.4.0
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # - name: KAFKA_BROKER_ID
            #   value: ""
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-svc:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(POD_NAME).kafka-svc:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"

          # command:
          #   - sh
          #   - -c
          #   - |
          #     export KAFKA_BROKER_ID=$(echo "${POD_NAME}" | awk -F'-' '{print $NF}')
          #     sed -i "s/^broker.id=.*/broker.id=${KAFKA_BROKER_ID}/" /etc/kafka/server.properties
          #     exec env KAFKA_BROKER_ID="${KAFKA_BROKER_ID}" /etc/confluent/docker/run

          ports:
            - containerPort: 9092
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: kafka-storage
        resources:
          requests:
            storage: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  ports:
    - port: 9092
  clusterIP: None
  selector:
    app: kafka
