# kafka.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  replicas: 3
  serviceName: kafka-svc
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        runAsUser: 0
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            - sh
            - -c
            - |
              chown -R 1000:1000 /var/lib/kafka/data
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.4.0
          env:
            # - name: KAFKA_BROKER_ID
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: metadata.name
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-svc:2181"
            # - name: KAFKA_ADVERTISED_LISTENERS
            #   value: "PLAINTEXT://kafka-0.kafka-svc:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - sh
            - -c
            - |
              export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://${POD_NAME}.kafka-svc:9092"
              export KAFKA_BROKER_ID=$(echo "${POD_NAME}"|awk -F'-' '{print $NF}')
              exec /etc/confluent/docker/run

          ports:
            - containerPort: 9092
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: kafka-storage
        resources:
          requests:
            storage: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  ports:
    - port: 9092
  clusterIP: None
  selector:
    app: kafka
