# zookeeper.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  replicas: 3
  serviceName: zookeeper-svc
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      securityContext:
        runAsUser: 0
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            - sh
            - -c
            - |
              chown -R 1000:1000 /var/lib/zookeeper/data && \
              echo $(( $(hostname | awk -F'-' '{print $NF}')+1 )) > /var/lib/zookeeper/data/myid
          volumeMounts:
            - name: zk-data
              mountPath: /var/lib/zookeeper/data
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.4.0
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            # - name: ZOOKEEPER_SERVER_ID
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: metadata.name
          ports:
            - containerPort: 2181
          volumeMounts:
            - name: zk-data
              mountPath: /var/lib/zookeeper/data
  volumeClaimTemplates:
    - metadata:
        name: zk-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: zookeeper-storage
        resources:
          requests:
            storage: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
spec:
  ports:
    - port: 2181
  clusterIP: None
  selector:
    app: zookeeper
